name: Bug Report
description: Report a problem with human.md
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Shell wrapper
        - Hook (PreToolUse)
        - Installer
        - Core (Python)
        - Core (Node)
        - Other
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "macOS 15.2 / Ubuntu 24.04 / ..."
    validations:
      required: true
  - type: input
    id: shell
    attributes:
      label: Shell
      placeholder: "zsh 5.9 / bash 5.2 / ..."
    validations:
      required: true
  - type: input
    id: runtime
    attributes:
      label: Runtime
      placeholder: "Python 3.12 / Node 22 / ..."
    validations:
      required: true
